#!/sbin/sh

###########################################WARNING############################################## 
##                                                                                            ##
## NO PERSONAL USE WITHOUT PERMISSION OF SkywalkerZ                                           ##
## ANY OTHER USE WITHOUT PERMISSION WILL BE REPORTED                                          ##
##                                                                                            ##
## YOU HAVE BEEN WARNED                                                                       ##
##                                                                                            ##
## PART OF SMARTDROID                                                                         ##
##                                                                                            ##
################################################################################################

mount /dev/block/mmcblk0p23 /system
mount /dev/block/mmcblk0p26 /data

cd /system/app
rm /system/app/AccuweatherPhone2014.apk 
rm /system/app/AccuweatherPhone2014.odex 
rm /system/app/WeatherDaemon2014.apk 
rm /system/app/WeatherDaemon2014.odex 

rm -r /data/dalvik-cache

exit

##By SkywalkerZ
## For Any Roms G900F KK