#!/sbin/sh

###########################################WARNING############################################## 
##                                                                                            ##
## NO PERSONAL USE WITHOUT PERMISSION OF SkywalkerZ                                           ##
## ANY OTHER USE WITHOUT PERMISSION WILL BE REPORTED                                          ##
##                                                                                            ##
## YOU HAVE BEEN WARNED                                                                       ##
##                                                                                            ##
## PART OF SMARTDROID                                                                         ##
##                                                                                            ##
################################################################################################

mount /dev/block/mmcblk0p23 /system
mount /dev/block/mmcblk0p26 /data

cd /system/app
rm /system/app/AllShareCastPlayer.apk
rm /system/app/AllShareCastPlayer.odex
rm /system/app/AllshareFileShare.apk
rm /system/app/AllshareFileShare.odex
rm /system/app/AllshareFileShareClient.apk
rm /system/app/AllshareFileShareClient.odex
rm /system/app/AllshareFileShareServer.apk
rm /system/app/AllshareFileShareServer.odex
rm /system/app/AllshareMediaServer.apk
rm /system/app/AllshareMediaServer.odex
rm /system/app/AllshareMediaShare.apk
rm /system/app/AllshareMediaShare.odex

rm -r /data/dalvik-cache

exit

##By SkywalkerZ
## For Any Roms G900F KK