#!/sbin/sh

###########################################WARNING############################################## 
##                                                                                            ##
## NO PERSONAL USE WITHOUT PERMISSION OF SkywalkerZ                                           ##
## ANY OTHER USE WITHOUT PERMISSION WILL BE REPORTED                                          ##
##                                                                                            ##
## YOU HAVE BEEN WARNED                                                                       ##
##                                                                                            ##
## PART OF SMARTDROID                                                                         ##
##                                                                                            ##
################################################################################################

mount /dev/block/mmcblk0p23 /system
mount /dev/block/mmcblk0p26 /data

cd /system/app
rm /system/app/KNOXAgent.apk 
rm /system/app/KNOXAgent.odex 
rm /system/app/KLMSAgent.apk 
rm /system/app/KLMSAgent.odex 
rm /system/app/KnoxAttestationAgent.apk 
rm /system/app/KnoxAttestationAgent.odex 
rm /system/app/KNOXStore.apk 
rm /system/app/KNOXStore.odex 
rm /system/app/KnoxSetupWizardClient.apk 
rm /system/app/KnoxSetupWizardClient.odex 
rm /system/app/KNOXStub.apk 
rm /system/app/KNOXStub.odex 

cd /system/priv-app
rm /system/priv-app/KLMSAgent.apk 
rm /system/priv-app/KLMSAgent.odex

cd /system/lib
rm /system/lib/libknoxdrawglfunction.so 

rm -r /data/dalvik-cache

exit

##By SkywalkerZ
## For Any Roms G900F KK