#!/sbin/sh

###########################################WARNING############################################## 
##                                                                                            ##
## NO PERSONAL USE WITHOUT PERMISSION OF SkywalkerZ                                           ##
## ANY OTHER USE WITHOUT PERMISSION WILL BE REPORTED                                          ##
##                                                                                            ##
## YOU HAVE BEEN WARNED                                                                       ##
##                                                                                            ##
## PART OF SMARTDROID                                                                         ##
##                                                                                            ##
################################################################################################

mount /dev/block/mmcblk0p23 /system
mount /dev/block/mmcblk0p26 /data

cd /system/app
rm /system/app/MobilePrint4.apk
rm /system/app/MobilePrint4.odex
rm /system/app/MobilePrintSvc_CUPSr.apk
rm /system/app/MobilePrintSvc_CUPS.apk
rm /system/app/MobilePrintSvc_CUPS_Backend
rm /system/app/MobilePrintSvc_Epson.apk
rm /system/app/MobilePrintSvc_HP.apk
rm /system/app/MobilePrintSvc_Samsung.apk
rm /system/app/MobilePrintSvc_WFDS.apk
cd /system/priv-app
cd /system/lib
cd /data/app/com.hp.android.printservice-1.apk
rm /data/app/com.sec.app.samsungprintservice-1.apk
rm /data/app/

rm -r /data/dalvik-cache

exit

##By SkywalkerZ
## For Any Roms G900F KK