#!/sbin/sh

###########################################WARNING############################################## 
##                                                                                            ##
## NO PERSONAL USE WITHOUT PERMISSION OF SkywalkerZ                                           ##
## ANY OTHER USE WITHOUT PERMISSION WILL BE REPORTED                                          ##
##                                                                                            ##
## YOU HAVE BEEN WARNED                                                                       ##
##                                                                                            ##
## PART OF SMARTDROID                                                                         ##
##                                                                                            ##
################################################################################################

mount /dev/block/mmcblk0p23 /system
mount /dev/block/mmcblk0p26 /data

cd /system/app
rm /system/app/PolarisViewer5.apk 
rm /system/app/PolarisOffice5.apk 
cd /system/priv-app
rm /system/priv-app/PolarisOffice5.apk 
cd /system/lib
rm /system/lib/libpolaristextprint5v.so
rm /system/lib/libpolarisviewer5.so
rm /system/lib/libpolarisviewerSDK.so
cd /data/app

rm -r /data/dalvik-cache

exit

##By SkywalkerZ
## For Any Roms G900F KK