#!/sbin/sh

###########################################WARNING############################################## 
##                                                                                            ##
## NO PERSONAL USE WITHOUT PERMISSION OF SkywalkerZ                                           ##
## ANY OTHER USE WITHOUT PERMISSION WILL BE REPORTED                                          ##
##                                                                                            ##
## YOU HAVE BEEN WARNED                                                                       ##
##                                                                                            ##
## PART OF SMARTDROID                                                                         ##
##                                                                                            ##
################################################################################################

mount /dev/block/mmcblk0p23 /system
mount /dev/block/mmcblk0p26 /data

cd /system/app
rm /system/app/BluetoothTest.apk
rm /system/app/SecFactoryPhoneTest.apk
rm /system/app/WlanTest.apk
rm /system/app/BluetoothTest.odex
rm /system/app/SecFactoryPhoneTest.odex
rm /system/app/WlanTest.odex
cd /system/priv-app
rm /system/priv-app/AutomationTest_FB.apk
rm /system/priv-app/DeviceTest.apk
rm /system/priv-app/HwModuleTest.apk
cd /system/lib
cd /data/app

rm -r /data/dalvik-cache

exit

##By SkywalkerZ
## For Any Roms G900F KK